### ISSUE TITLE
scripts-bundled.js cause fatal error in wordpress

### ISSUE THREAD

**Issue by sparkbold** [LearnWebCode/university-static#1]
Here is the code I follow to enqueue in WP: `wp_enqueue_scripts('main-university-js', get_theme_file_uri( '/js/scripts-bundled.js' ),NULL,microtime(),true);`

And here is error: `Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /app/public/wp-includes/class-wp-hook.php on line 288`

_Note: I use Flywheel for local WP Dev. PHP Memory 256MB which I think is most common setting on hosting server. When comment out the code the site work fine._

**Comment by geniuskouta** [comment]
Yes, I am facing the same problem. I tried to assign more memory from wp-config.php but it didn't work out.
