### ISSUE TITLE
scripts-bundled.js not loading slider

### ISSUE THREAD

**Issue by JG-devo** [LearnWebCode/university-static#6]
Adding the script to functions.php:

p_enqueue_script('main-uni-js', get_theme_file_uri('/js/scripts-bundled.js'), NULL, '1.0', true);

google console reports:

`Uncaught TypeError: Cannot read property 'insertAdjacentHTML' of null
    at new Y (scripts-bundled.js:6)
    at Module.<anonymous> (scripts-bundled.js:6)
    at n (scripts-bundled.js:1)
    at scripts-bundled.js:1
    at scripts-bundled.js:1`

**Comment by LearnWebCode** [comment]
Hi, please make sure you also use the absolutely newest version of the <div class="hero-slider"></div> HTML found in the index.html file. Also, please use the newest css from style.css in the root of this repo. Also, I'd re-copy over the entire CSS folder and JS folder.

**Comment by JG-devo** [comment]
It seems there was an update to the package (after I raised the issue) which has resolved the slider. The static site wasn't even loading the slider outside of wordpress originally but it seems to be resolved now.

**Comment by aadilayub** [comment]
I'm facing this issue as well, but am getting a different error

```
Uncaught Error: Module parse failed: Unexpected character '@' (2:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /* 3rd party packages */
> @import "normalize.css";
| @import "../node_modules/@glidejs/glide/dist/css/glide.core.min.css";
| 
```

Have already cloned and updated the latest files
